### ISSUE TITLE
Ability to input database information

### ISSUE THREAD

**Issue by chaukap** [chaukap/capstone_team_4#1]
User Story
-------
As a user, I would like a web form where I can input database information so that the web application can extract table information from the database.

Technical Info
-------
* This web page should be served from the root of the website. 
* The required fields are
        1) username : str,
        2) password : str,
        3) host : str,
        4) database : str,
        5) table : str
* An additional field, port : str, should be optional and default to 3306 if no port is specified.
* When the user clicks "Submit" the information should be sent to the "/table" endpoint (which is connected to the `get_schema()` function in the flask app).

**Comment by kks37405** [comment]
Created a form in index.html that points to /table when clicking submit. When I enter information I get "Database not specified" using the following credentials: 
URI: capstone-team-4-dev.cpbxzomz7uyl.us-east-2.rds.amazonaws.com
User: admin
Password: testpassword
Database: sys
Table: Arrests
Port: 3306

**Comment by chaukap** [comment]
@kks37405 Everything looks correct when I review the code on Github, so there might be a problem with the backend. I'll have some time later today to take a crack at troubleshooting.

**Comment by chaukap** [comment]
@kks37405 Found the problem- in addition to specifying an `id` attribute in the `input` elements, you must specify a `name` attribute or the field [won't be sent at all](https://www.w3schools.com/html/html_forms.asp). I committed the fix [here](https://github.com/chaukap/capstone_team_4/commit/5143cfd292962fff76831ba3780b242f812b6416) if you'd like to take a look!

**Comment by kks37405** [comment]
Got it, thanks for the help.

**Comment by chaukap** [comment]
Thank you for the work. The UI looks incredible, and this story is complete! We can discuss the next steps tomorrow.
